apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: <SERVICE-NAMESPACE-VALUE>
spec:
  request: <SERVER-CSR-VALUE>
  signerName: <SIGNER-NAME>
  usages:
  - digital signature
  - key encipherment
  - server auth
