# Camunda Keycloak Identity Provider Plugin
plugin.identity.keycloak:
  keycloakIssuerUrl: https://camunda-keycloak/auth/realms/camunda
  keycloakAdminUrl: https://camunda-keycloak/auth/admin/realms/camunda
  clientId: camunda-identity-service
  clientSecret: LtObO5ILz9qPr2CkcfaBp7FsZ6Q1WzCN
  useUsernameAsCamundaUserId: true
  useGroupPathAsCamundaGroupId: true
  administratorGroupName: camunda-admin
  disableSSLCertificateValidation: true
