apiVersion: apps/v1
kind: Deployment
metadata:
  name: apacheds
  labels:
    app: apacheds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apacheds
  template:
    metadata:
      labels:
        app: apacheds
    spec:
      containers:
        - name: apacheds
          image: openfrontier/apacheds
          volumeMounts:
            - name: ldifs
              mountPath: /conf/seed.ldif
              subPath: seed.ldif
          ports:
            - containerPort: 10389
              name: ldap
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "set -e; apt-get update && apt-get install ldap-utils -y && ldapmodify -c -a -f /conf/seed.ldif -h localhost -p 10389 -D \"uid=admin,ou=system\" -w 'secret'"]
      volumes:
        - name: ldifs
          configMap:
            name: camunda-ldif
